### PR TITLE
Fix networking on esp idf v5.x

### LINKED ISSUE #126: Networking isn't compatible with esp-idf 5.x
When building with ESP-IDF version: v5.2.2, I'm getting the warning "Networking isn't compatible with esp-idf 5.x" and indeed, this isn't compiled in.

What would it take to get the networking to work again with ESP-IDF v5.x?

As more and more projects are moving to that latest version, including the MicroPython that the Fri3D Camp 2024 badge uses, it would be great to get that working again :-)

### PR DESCRIPTION
**Pull request by tomvanbraeckel**
Untested with ESP-IDF v4.x but it should work there as well.

Note that I had to set the launcher LOG_DEFAULT_LEVEL to LOG_DEFAULT_LEVEL_ERROR to prevent it from defaulting to LOG_DEFAULT_LEVEL_INFO, otherwise the launcher.bin size would be > 1MB, which only fits if PARTITION_TABLE_SINGLE_APP_LARGE (1.5MB) is set instead of the default PARTITION_TABLE_SINGLE_APP (1MB).

To change this:
 
```
cd launcher/
idf.py menuconfig # use the / key to search
```
To further reduce the size of the binary, there are some hints at https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/performance/size.html#wi-fi

Fixes #126

### CODE REVIEW

**Comment by ducalex** [comment]
All current targets use `CONFIG_LOG_DEFAULT_LEVEL_WARN` for this reason, INFO makes everything huge.

Does idf complain when the binary is larger than its partition? Retro-go doesn't care about idf's partition table but it might be worth defining `PARTITION_TABLE_SINGLE_APP_LARGE=y` anyway if idf refuses to build larger than 1MB.

File: components/retro-go/rg_network.c [hunk 1]
```diff
@@ -277,8 +283,7 @@ bool rg_network_init(void)
     // Init event loop first
     esp_err_t err;
     TRY(esp_event_loop_create_default());
-    TRY(esp_event_handler_register(WIFI_EVENT, ESP_EVENT_ANY_ID, &network_event_handler, NULL));
-    TRY(esp_event_handler_register(IP_EVENT, IP_EVENT_STA_GOT_IP, &network_event_handler, NULL));
+    TRY(esp_event_handler_register(ESP_EVENT_ANY_BASE, ESP_EVENT_ANY_ID, &network_event_handler, NULL));
```
Comment (ducalex) [inline components/retro-go/rg_network.c:286]: Switching to `ESP_EVENT_ANY_ID` is a good idea but are you sure it's necessary to switch to `ESP_EVENT_ANY_BASE`?

The event loop is used for more than networking so listening only for what we need seems better. Is it because esp-idf removed the constants `WIFI_EVENT` and `IP_EVENT`?

**Comment by ducalex** [comment]
I suppose in an ideal world we'd feed idf our custom partition map but I never found how to tell esp-idf which partition should be used when flashing that specific app through idf.

I'll do some testing with `PARTITION_TABLE_SINGLE_APP_LARGE`, make sure it is safetly ignored by 4.3 and then I'll add that until if/when we manage to make it work with our real partition table.

**Comment by ducalex** [comment]
Otherwise the PR looks good and I'm happy to merge, I just left a final question.

File: components/retro-go/rg_network.c (hunk 1 above)
Comment (ducalex) [reply components/retro-go/rg_network.c]: Thanks that seems perfect.

**Comment by ducalex** [comment]
Thanks!
